### PR TITLE
Reduce image size

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
1.06GB instead of 1.69GB. Could probably get smaller.

**Comment by ImreSamu** [comment]
@stirringhalo 
I would prefer if we can use the same GEOS version everywhere. 
* imposm3 side, 
* Postgis side
* in the import process ( import-water, import-osmborder,  import-natural-earth, ... ) 

As I see  this is using GEOS=3.4.2 vs. GEOS=3.6 in https://github.com/openmaptiles/postgis 

```
Setting up libgeos-3.4.2 (3.4.2-6) ...
Setting up libgeos-c1 (3.4.2-6) ...
```

This in not a strict requirements, so no problem if we use different GEOS versions. 
but sometimes this makes the system very hard to debug.

**Comment by ghost** [comment]
@ImreSamu Good point. After I cleanup openmaptiles/postgres (and if the size is reasonable), I will probably switch back.

**Comment by ImreSamu** [comment]
@stirringhalo 
the docker real size / shared size / unique size is different.
if we use the same base image - then the **real disk usage** will be smaller.


```
$ docker system  df -v | grep openmaptiles
REPOSITORY                          TAG                 IMAGE ID            CREATED ago         SIZE                SHARED SIZE         UNIQUE SiZE         CONTAINERS

openmaptiles/openmaptiles-tools     latest              ed5fad49ce84        3 days ago ago      709.2MB             688.9MB             20.22MB             0
openmaptiles/openmaptiles-tools     0.5                 36092b93e5c2        10 days ago ago     709.2MB             688.9MB             20.22MB             0
openmaptiles/postserve              0.1                 9d06ce451ff5        3 weeks ago ago     712.3MB             621.7MB             90.61MB             0
openmaptiles/postgis                2.5                 5ce5e5d9f1c9        4 weeks ago ago     2.316GB             0B                  2.316GB             1
openmaptiles/import-water           0.4                 1aeb1f3806ca        7 weeks ago ago     1.687GB             0B                  1.687GB             0
openmaptiles/import-osm             0.4                 3c835f185b81        2 months ago ago    857.3MB             0B                  857.3MB             0
openmaptiles/generate-vectortiles   0.1.1               f744d2dc758c        4 months ago ago    771.3MB             0B                  771.3MB             0
openmaptiles/import-osmborder       0.2                 9a7cb57842ab        4 months ago ago    3.026GB             1.016GB             2.01GB              0
openmaptiles/generate-osmborder     latest              4aa7bdd5f6c2        4 months ago ago    532.8MB             123MB               409.8MB             0
openmaptiles/import-natural-earth   1.2                 230deada58f4        5 months ago ago    425.7MB             123MB               302.6MB             0
openmaptiles/import-sql             0.1                 0abd92d95e0f        6 months ago ago    1.023GB             264.7MB             758.4MB             0
openmaptiles/postgis                2.3                 5fe38e5de1b7        6 months ago ago    1.016GB             1.016GB             0B                  0
openmaptiles/import-lakelines       0.9                 049e1ee8e9e1        6 months ago ago    247MB               123MB               124MB               0
```

now we are using different base images, and the SHARED LAYERS not optimal.

**Comment by ghost** [comment]
Actually now, with import-water I have the following:

```
import-water                        latest              e28dbd6e71cd        50 minutes ago      1.063 GB            266.8 MB            796.7 MB            0
openmaptiles/import-water           0.4                 1aeb1f3806ca        7 weeks ago         1.687 GB            0 B                 1.687 GB            0
```
So it's a bit smaller (import-water is the PR). 

Import-water used the openmaptiles/postgres:2.2, which is different from the main openmaptiles/postgres:2.8 and so it really isn't efficient.
Across all the docker images, it's probably a net win (and reduces the layers) though it would be indeed worth it to go back to a massively reduced openmaptiles/postgis to have matching GEOS versions.

**Comment by ghost** [comment]
I am merging now, but I will investigate using openmaptiles/postgres for matching GEOS versions if I can do it efficiently (and easily track the version)

**Pull request merged**
